### ISSUE TITLE
weird work of the launcher "out of the box"

### ISSUE THREAD

**Issue by PinyaGit** [mbpictures/GameUpdater#7]
Freshly downloaded source code downloads abc.mp4 file, after restarting the launcher, it deletes it and downloads it again.

**Comment by mbpictures** [comment]
Hi! Thanks for reporting this issue and sorry for the delayed answer. I'll investigate in this issue soon, but it would help a lot if you could add some details. Maybe you can share the manifest xml your are using, the path you are executing the launcher in and the files/folders located in the same directory. Thank you already!

**Comment by mbpictures** [comment]
Hi again! Thanks for bringing this issue to my attention. I actually figured out, what caused the issue:
samplelib.com changed the sample video file (which is downloaded by the Updater), so the MD5 & SHA1 checksum in the manifest was not up to date anymore. Because of that, the Updater always marks the file as corrupt (as the checksums don't match). I updated the example manifest on the server, the issue should be gone.
